//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheRoad.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Continent
    {
        public Continent()
        {
            this.Travels = new HashSet<Travel>();
        }
    
        public int ContinentId { get; set; }
        public string ContinentName { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual ICollection<Travel> Travels { get; set; }
    }
}
