//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheRoad.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int TravelId { get; set; }
        public string TravelName { get; set; }
        public string ShortTitle { get; set; }
        public string Description { get; set; }
        public string Outline { get; set; }
        public int ContinentId { get; set; }
        public string ImageUrl { get; set; }
        public int Duration { get; set; }
        public bool IsPopular { get; set; }
    
        public virtual Continent Continent { get; set; }
    }
}
